language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt
env:
  global:
    - APP_SECRET_KEY=supersecretkey
    - JWT_SECRET_KEY=supersecretkey

script:
  - python -m unittest
